apiVersion: 1
contactPoints:
    - orgId: 1
      name: MusicAlert_bot
      receivers:
        - uid: df74nvl89o074e
          type: telegram
          settings:
            bottoken: ${MYTGRAM_BOTTOKEN}
            chatid: >
              ${MYTGRAM_CHATID}
            disable_notification: false
            disable_web_page_preview: false
            protect_content: false
          disableResolveMessage: true
