apiVersion: 1
policies:
    - orgId: 1
      receiver: MusicAlert_bot
      group_by:
        - grafana_folder
        - alertname
      group_wait: 0s
      group_interval: 5m
      repeat_interval: 10m
